version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html