version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432"
    volumes:
      - ./db-persistent-data:/var/lib/postgresql/data/
